//! Token utility functions: HMAC-SHA256 hashing and random token generation.
//!
//! # JWT tokens
//!
//! JWT creation and verification live exclusively in `crate::middleware::auth`
//! (`create_token_with_kid`, `verify_token_with_secrets`). The `Claims` struct
//! and all JWT helpers were consolidated there to avoid having two diverging
//! implementations. Do **not** add JWT logic back to this module.
//!
//! # What belongs here
//!
//! Stateless, non-JWT token utilities:
//! - `hash_token` / `verify_token_hash` — HMAC-SHA256 hashing for refresh,
//!   confirmation, and password-reset tokens stored in the database.
//! - `generate_random_token` — cryptographically-secure random token strings.

/// Prefix identifying HMAC-SHA256 hashes (new format).
const HMAC_PREFIX: &str = "hmac:";

/// Hash a token using HMAC-SHA256 with the provided key.
///
/// Tokens (refresh, confirmation, password-reset) are high-entropy random strings
/// generated by `OsRng`. They don't need slow password-hashing like Argon2id —
/// HMAC-SHA256 is sufficient and ~1000x faster (~microseconds vs ~seconds).
///
/// Output format: `hmac:<hex_hmac>` (deterministic, no per-token salt needed).
pub fn hash_token(token: &str, key: &str) -> String {
    use hmac::{Hmac, Mac};
    use sha2::Sha256;

    type HmacSha256 = Hmac<Sha256>;

    let mut mac = HmacSha256::new_from_slice(key.as_bytes()).expect("HMAC accepts any key length");
    mac.update(token.as_bytes());
    let result = mac.finalize();
    format!("{}{}", HMAC_PREFIX, hex::encode(result.into_bytes()))
}

/// Verify a token against a stored hash.
///
/// Uses HMAC-SHA256 for fast (~µs) token verification.
/// All tokens are now stored with `hmac:` prefix format.
///
/// Legacy Argon2id hashes have been migrated: refresh tokens rotate to HMAC format
/// on each use, ensuring transparent migration without forcing user logout.
pub fn verify_token_hash(token: &str, stored: &str, key: &str) -> bool {
    if !stored.starts_with(HMAC_PREFIX) {
        // Non-HMAC hashes are invalid - migration should have occurred
        tracing::warn!(
            event = "token.legacy_hash_detected",
            "Token stored with legacy Argon2id hash format. Should have been migrated to HMAC-SHA256."
        );
        return false;
    }
    verify_hmac(token, stored, key)
}

fn verify_hmac(token: &str, stored: &str, key: &str) -> bool {
    use hmac::{Hmac, Mac};
    use sha2::Sha256;

    type HmacSha256 = Hmac<Sha256>;

    let stored_hex = &stored[HMAC_PREFIX.len()..];
    let expected = match hex::decode(stored_hex) {
        Ok(b) => b,
        Err(_) => return false,
    };

    let mut mac = HmacSha256::new_from_slice(key.as_bytes()).expect("HMAC accepts any key length");
    mac.update(token.as_bytes());
    let computed = mac.finalize().into_bytes();

    subtle::ConstantTimeEq::ct_eq(&computed[..], &expected[..]).into()
}

pub fn generate_random_token(length: usize) -> String {
    use rand::Rng;
    use rand::rngs::OsRng;
    const CHARSET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let mut rng = OsRng;
    (0..length)
        .map(|_| {
            let idx = rng.gen_range(0..CHARSET.len());
            CHARSET[idx] as char
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hash_token_deterministic() {
        let token = "test-refresh-token-12345";
        let key = "test_key";
        let hash1 = hash_token(token, key);
        let hash2 = hash_token(token, key);

        // HMAC-SHA256 is deterministic: same input + same key = same hash
        assert_eq!(hash1, hash2);
        assert!(hash1.starts_with("hmac:"));
    }

    #[test]
    fn test_hash_token_different_inputs() {
        let key = "test_key";
        let hash1 = hash_token("token1", key);
        let hash2 = hash_token("token2", key);

        assert_ne!(hash1, hash2);
    }

    #[test]
    fn test_hash_token_different_keys() {
        let token = "test-refresh-token-12345";
        let hash1 = hash_token(token, "key1");
        let hash2 = hash_token(token, "key2");

        assert_ne!(hash1, hash2);
    }

    #[test]
    fn test_verify_token_hash() {
        let token = "test-refresh-token-12345";
        let key = "test_key";
        let stored = hash_token(token, key);

        assert!(verify_token_hash(token, &stored, key));
        assert!(!verify_token_hash("wrong-token", &stored, key));
    }

    #[test]
    fn test_verify_token_hash_wrong_key() {
        let token = "test-refresh-token-12345";
        let stored = hash_token(token, "correct-key");

        assert!(!verify_token_hash(token, &stored, "wrong-key"));
    }

    #[test]
    fn test_generate_random_token_length() {
        let token = generate_random_token(32);
        assert_eq!(token.len(), 32);
    }

    #[test]
    fn test_generate_random_token_uniqueness() {
        let token1 = generate_random_token(48);
        let token2 = generate_random_token(48);

        assert_ne!(token1, token2);
    }

    #[test]
    fn test_generate_random_token_charset() {
        let token = generate_random_token(100);
        assert!(token.chars().all(|c| c.is_ascii_alphanumeric()));
    }
}
