#![allow(dead_code)]

use crate::errors::AppResult;
#[allow(unused_imports)]
use crate::models::user::User;
#[allow(unused_imports)]
use crate::security::SecurityService;
use chrono::Utc;
use jsonwebtoken::{Algorithm, DecodingKey, EncodingKey, Header, Validation, decode, encode};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Serialize, Deserialize)]
pub struct Claims {
    pub sub: Uuid,
    pub profile_id: Uuid,
    pub role: i32,
    pub exp: usize,
    pub iat: usize,
    pub jti: Option<String>,
}

pub fn create_token(
    user_id: Uuid,
    profile_id: Uuid,
    role_claim: i32,
    jwt_secret: &str,
    expiry_secs: i64,
) -> AppResult<String> {
    let now = Utc::now().timestamp() as usize;
    let claims = Claims {
        sub: user_id,
        profile_id,
        role: role_claim,
        exp: now + expiry_secs as usize,
        iat: now,
        jti: Some(uuid::Uuid::new_v4().to_string()),
    };
    let token = encode(
        &Header::default(),
        &claims,
        &EncodingKey::from_secret(jwt_secret.as_ref()),
    )?;
    Ok(token)
}

pub fn verify_token(token: &str, jwt_secret: &str) -> AppResult<Claims> {
    let token_data = decode::<Claims>(
        token,
        &DecodingKey::from_secret(jwt_secret.as_ref()),
        &Validation::new(Algorithm::HS256),
    )?;
    Ok(token_data.claims)
}

/// Prefix identifying HMAC-SHA256 hashes (new format).
const HMAC_PREFIX: &str = "hmac:";

/// Hash a token using HMAC-SHA256 with the provided key.
///
/// Tokens (refresh, confirmation, password-reset) are high-entropy random strings
/// generated by `OsRng`. They don't need slow password-hashing like Argon2id —
/// HMAC-SHA256 is sufficient and ~1000x faster (~microseconds vs ~seconds).
///
/// Output format: `hmac:<hex_hmac>` (deterministic, no per-token salt needed).
pub fn hash_token(token: &str, key: &str) -> String {
    use hmac::{Hmac, Mac};
    use sha2::Sha256;

    type HmacSha256 = Hmac<Sha256>;

    let mut mac = HmacSha256::new_from_slice(key.as_bytes()).expect("HMAC accepts any key length");
    mac.update(token.as_bytes());
    let result = mac.finalize();
    format!("{}{}", HMAC_PREFIX, hex::encode(result.into_bytes()))
}

/// Verify a token against a stored hash.
///
/// Uses HMAC-SHA256 for fast (~µs) token verification.
/// All tokens are now stored with `hmac:` prefix format.
///
/// Legacy Argon2id hashes have been migrated: refresh tokens rotate to HMAC format
/// on each use, ensuring transparent migration without forcing user logout.
pub fn verify_token_hash(token: &str, stored: &str, key: &str) -> bool {
    if !stored.starts_with(HMAC_PREFIX) {
        // Non-HMAC hashes are invalid - migration should have occurred
        tracing::warn!(
            event = "token.legacy_hash_detected",
            "Token stored with legacy Argon2id hash format. Should have been migrated to HMAC-SHA256."
        );
        return false;
    }
    verify_hmac(token, stored, key)
}

fn verify_hmac(token: &str, stored: &str, key: &str) -> bool {
    use hmac::{Hmac, Mac};
    use sha2::Sha256;

    type HmacSha256 = Hmac<Sha256>;

    let stored_hex = &stored[HMAC_PREFIX.len()..];
    let expected = match hex::decode(stored_hex) {
        Ok(b) => b,
        Err(_) => return false,
    };

    let mut mac = HmacSha256::new_from_slice(key.as_bytes()).expect("HMAC accepts any key length");
    mac.update(token.as_bytes());
    let computed = mac.finalize().into_bytes();

    subtle::ConstantTimeEq::ct_eq(&computed[..], &expected[..]).into()
}

pub fn generate_random_token(length: usize) -> String {
    use rand::Rng;
    use rand::rngs::OsRng;
    const CHARSET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let mut rng = OsRng;
    (0..length)
        .map(|_| {
            let idx = rng.gen_range(0..CHARSET.len());
            CHARSET[idx] as char
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_create_and_verify_token() {
        let user_id = Uuid::new_v4();
        let profile_id = Uuid::new_v4();
        let role_claim = 1;
        let jwt_secret = "test-secret-key-for-testing-only";
        let expiry_secs = 3600;

        let token = create_token(user_id, profile_id, role_claim, jwt_secret, expiry_secs).unwrap();
        let claims = verify_token(&token, jwt_secret).unwrap();

        assert_eq!(claims.sub, user_id);
        assert_eq!(claims.profile_id, profile_id);
        assert_eq!(claims.role, role_claim);
    }

    #[test]
    fn test_verify_token_fails_with_wrong_secret() {
        let user_id = Uuid::new_v4();
        let profile_id = Uuid::new_v4();
        let role_claim = 1;
        let jwt_secret = "test-secret-key-for-testing-only";
        let wrong_secret = "wrong-secret";
        let expiry_secs = 3600;

        let token = create_token(user_id, profile_id, role_claim, jwt_secret, expiry_secs).unwrap();
        let result = verify_token(&token, wrong_secret);

        assert!(result.is_err());
    }

    #[test]
    fn test_hash_token_deterministic() {
        let token = "test-refresh-token-12345";
        let key = "test_key";
        let hash1 = hash_token(token, key);
        let hash2 = hash_token(token, key);

        // HMAC-SHA256 is deterministic: same input + same key = same hash
        assert_eq!(hash1, hash2);
        assert!(hash1.starts_with("hmac:"));
    }

    #[test]
    fn test_hash_token_different_inputs() {
        let key = "test_key";
        let hash1 = hash_token("token1", key);
        let hash2 = hash_token("token2", key);

        assert_ne!(hash1, hash2);
    }

    #[test]
    fn test_hash_token_different_keys() {
        let token = "test-refresh-token-12345";
        let hash1 = hash_token(token, "key1");
        let hash2 = hash_token(token, "key2");

        assert_ne!(hash1, hash2);
    }

    #[test]
    fn test_verify_token_hash() {
        let token = "test-refresh-token-12345";
        let key = "test_key";
        let stored = hash_token(token, key);

        assert!(verify_token_hash(token, &stored, key));
        assert!(!verify_token_hash("wrong-token", &stored, key));
    }

    #[test]
    fn test_verify_token_hash_wrong_key() {
        let token = "test-refresh-token-12345";
        let stored = hash_token(token, "correct-key");

        assert!(!verify_token_hash(token, &stored, "wrong-key"));
    }

    #[test]
    fn test_generate_random_token_length() {
        let token = generate_random_token(32);
        assert_eq!(token.len(), 32);
    }

    #[test]
    fn test_generate_random_token_uniqueness() {
        let token1 = generate_random_token(48);
        let token2 = generate_random_token(48);

        assert_ne!(token1, token2);
    }

    #[test]
    fn test_generate_random_token_charset() {
        let token = generate_random_token(100);
        assert!(token.chars().all(|c| c.is_ascii_alphanumeric()));
    }
}
